apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: airbnb-pejt-domov
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - airbnbpejtdomov.djnd.si
        - airbnbpejtdomov.danesjenovdan.si
      secretName: airbnb-pejt-domov-tls
  rules:
    - host: airbnbpejtdomov.djnd.si
      http: &http_paths
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: airbnb-pejt-domov
                port:
                  number: 3000
    - host: airbnbpejtdomov.danesjenovdan.si
      http: *http_paths
