apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: airbnb
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: airbnb-pejt-domov
    newName: rg.fr-par.scw.cloud/djnd/airbnb-pejt-domov-aka-ljudem-mesta
    newTag: "latest"
